#!/usr/bin/env sh
wget -O dropbox.py https://www.dropbox.com/download?dl=packages/dropbox.py
chmod 500 dropbox.py 

./dropbox.py start --install
sleep 3s
./dropbox.py lansync n
sleep 3s
./dropbox.py start
sleep 3s
./dropbox.py stop
sleep 3s

echo "You should access to link and then input your DropBox account and password."
echo "And execute commmand \"./drobox.py start\""

